# Generated by Django 3.0 on 2019-12-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='introduction',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
